# StsSelfUseMod 配置文件
# 修改数值后重启游戏生效。
# 功能标志：true为开启，false为关闭

[StartingState]
# 全局额外初始能量（0为不修改）
ExtraEnergy = 0

# 全角色额外起始金币
ExtraGold = 900

[ShopState]
# 零费删卡标志
ZeroRemoveFlag = true

# 无限删卡标志
InfiniteRemoveFlag = true

[OtherState]
# 战斗后奖励额外卡牌数（数值在【-2，2】之间，0为不修改）
ExtraCardNum = 1

# 自定义锻造升级卡牌功能
InfiniteSmithFlag = true
# 锻造卡牌数(InfiniteSmithFlag=false时，该值设定无效)，<=0为全部卡牌，>0的值为必选升级卡牌数（设定后，必须选择设定数值的卡牌数升级，自动限定不超过可升级卡牌数）
SmithNum = 0

[CardState]

# 残影升级格挡保留额外提升1回合
BlurUpgradeFlag = true

# 涂毒升级耗能减1，中毒额外加1
EnvenomUpgradeFlag = true

# 杂技回滚为普通卡
AcrobaticsRarityRestoreFlag = true

# 挽歌升级去除消耗
DirgeUpgradeFlag = true

# 生产制造升级去除消耗
ProductionUpgradeFlag = true

# 至亮之焰升级不再消耗最大生命
BrightestFlameUpgradeFlag = true

[EventsState]
# 湿滑木桥是否掉血
BridgeLossHpFlag = true

# 自定义石中剑精英数量(1-5，0为不修改)
SwordOfStoneElitenNum = 1